# docker-compose.yaml
services:
  adminer:
    logging:
      driver: ${LOGGER_DRIVER}
      options:
        max-size: ${MAX_SIZE}
        max-file: ${MAX_FILE}
    image: ghcr.io/alexanderjkochnev/adminer:4.8.1
    restart: unless-stopped
    environment:
      - ADMINER_PLUGINS=tables-filter enum-option enum-types
      - ADMINER_DESIGN=nette
    ports:
      - "${ADMINER_PORTS}"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '1'
          memory: 512M
    networks:
      postgres_network:
        ipv4_address: ${IP_POSTGRES}

networks:
  postgres_network:
    driver: bridge
    ipam:
      config:
        - subnet: ${SUBNET_POSTGRES}
